-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 21:21:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mande
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mande
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mande` DEFAULT CHARACTER SET utf8 ;
USE `mande` ;

-- -----------------------------------------------------
-- Table `mande`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`service` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `name_service` VARCHAR(45) NOT NULL,
  `detail_service` VARCHAR(255) NOT NULL,
  `image_service` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`account` (
  `id_account` INT NOT NULL AUTO_INCREMENT,
  `email_account` VARCHAR(45) NOT NULL,
  `password_account` VARCHAR(255) NOT NULL,
  `dateregister_account` DATETIME NOT NULL,
  `dateupdate_account` DATETIME NOT NULL,
  `isadmin_account` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_account`),
  UNIQUE INDEX `email_UNIQUE` (`email_account` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`image` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `url_image` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `account_id_account` INT NOT NULL,
  `image_id_image` INT NOT NULL DEFAULT 1,
  `name_user` VARCHAR(45) NOT NULL,
  `lastname_user` VARCHAR(45) NOT NULL,
  `phone_user` VARCHAR(10) NOT NULL,
  `dateregister_user` DATETIME NOT NULL,
  `dateupdate_user` DATETIME NOT NULL,
  `ismander_user` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_account_idx` (`account_id_account` ASC) VISIBLE,
  INDEX `fk_user_image1_idx` (`image_id_image` ASC) VISIBLE,
  CONSTRAINT `fk_user_account`
    FOREIGN KEY (`account_id_account`)
    REFERENCES `mande`.`account` (`id_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_image1`
    FOREIGN KEY (`image_id_image`)
    REFERENCES `mande`.`image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`request` (
  `id_request` INT NOT NULL AUTO_INCREMENT,
  `service_id_service` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  `detail_request` VARCHAR(255) NOT NULL,
  `status_request` ENUM('Pendiente', 'Proceso', 'Finalizado') NOT NULL DEFAULT 'Pendiente',
  `dateregister_request` DATETIME NOT NULL,
  `dateupdate_request` DATETIME NOT NULL,
  PRIMARY KEY (`id_request`),
  INDEX `fk_request_service1_idx` (`service_id_service` ASC) VISIBLE,
  INDEX `fk_request_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_request_service1`
    FOREIGN KEY (`service_id_service`)
    REFERENCES `mande`.`service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_request_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mande`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`mander`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`mander` (
  `id_mander` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `image_id_image` INT NOT NULL DEFAULT 1,
  `ishavecar_mander` TINYINT(1) NOT NULL,
  `ishavemoto_mander` TINYINT(1) NOT NULL,
  `isactive_mander` TINYINT(1) NOT NULL,
  `isvalidate_mander` TINYINT(1) NOT NULL DEFAULT 0,
  `dateregister_mander` DATETIME NOT NULL,
  `dateupdate_mander` DATETIME NOT NULL,
  `address_mander` VARCHAR(100) NOT NULL,
  `cc_mander` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`id_mander`),
  INDEX `fk_mander_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_mander_image1_idx` (`image_id_image` ASC) VISIBLE,
  CONSTRAINT `fk_mander_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mande`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mander_image1`
    FOREIGN KEY (`image_id_image`)
    REFERENCES `mande`.`image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`requestmanager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`requestmanager` (
  `id_requestmanager` INT NOT NULL AUTO_INCREMENT,
  `request_id_request` INT NOT NULL,
  `image_id_image` INT NOT NULL DEFAULT 1,
  `mander_id_mander` INT NOT NULL,
  `status_requestmanager` ENUM('espera', 'proceso', 'terminado') NOT NULL,
  `detail_requestmanager` VARCHAR(45) NOT NULL,
  `dateregister_requestmanager` DATETIME NOT NULL,
  `dateupdate_requestmanager` DATETIME NOT NULL,
  PRIMARY KEY (`id_requestmanager`),
  INDEX `fk_requestmanager_request1_idx` (`request_id_request` ASC) VISIBLE,
  INDEX `fk_requestmanager_image1_idx` (`image_id_image` ASC) VISIBLE,
  INDEX `fk_requestmanager_mander1_idx` (`mander_id_mander` ASC) VISIBLE,
  CONSTRAINT `fk_requestmanager_request1`
    FOREIGN KEY (`request_id_request`)
    REFERENCES `mande`.`request` (`id_request`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requestmanager_image1`
    FOREIGN KEY (`image_id_image`)
    REFERENCES `mande`.`image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requestmanager_mander1`
    FOREIGN KEY (`mander_id_mander`)
    REFERENCES `mande`.`mander` (`id_mander`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `url_document` VARCHAR(255) NOT NULL,
  `isdocument_vehicle` TINYINT(1) NOT NULL,
  `isverified_document` TINYINT(1) NOT NULL,
  `type_document` ENUM('CC', 'SOAT', 'LICENCIA', 'OPERACION', 'TECNOMECANICA', 'RECIBO') NOT NULL,
  `dateregister_document` DATETIME NOT NULL,
  `dateupdate_document` DATETIME NOT NULL,
  `dateverified_document` DATETIME NOT NULL,
  PRIMARY KEY (`id_document`),
  INDEX `fk_document_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_document_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mande`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mande`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mande`.`vehicle` (
  `id_vehicle` INT NOT NULL AUTO_INCREMENT,
  `user_id_user` INT NOT NULL,
  `image_id_image` INT NOT NULL DEFAULT 1,
  `brand_vehicle` VARCHAR(20) NOT NULL,
  `plate_vehicle` VARCHAR(10) NOT NULL,
  `model_vehicle` SMALLINT(4) NOT NULL,
  `color_vehicle` VARCHAR(45) NOT NULL,
  `type_vehicle` ENUM('ninguno', 'bicicle', 'bike', 'car') NOT NULL,
  `isverified_vehicle` TINYINT(1) NOT NULL,
  `dateregister_vehicle` DATETIME NOT NULL,
  `dateupdate_vehicle` DATETIME NOT NULL,
  `dateverified_vehicle` DATETIME NOT NULL,
  PRIMARY KEY (`id_vehicle`),
  INDEX `fk_vehicle_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_vehicle_image1_idx` (`image_id_image` ASC) VISIBLE,
  CONSTRAINT `fk_vehicle_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mande`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_image1`
    FOREIGN KEY (`image_id_image`)
    REFERENCES `mande`.`image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mande`.`image`
-- -----------------------------------------------------
START TRANSACTION;
USE `mande`;
INSERT INTO `mande`.`image` (`id_image`, `url_image`) VALUES (NULL, 'https://upload.wikimedia.org/wikipedia/commons/2/2c/Default_pfp.svg');

COMMIT;

