# Generated by Django 4.2.7 on 2023-11-24 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.AutoField(primary_key=True, serialize=False)),
                ('email_account', models.CharField(max_length=45, unique=True)),
                ('password_account', models.CharField(max_length=255)),
                ('dateregister_account', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_account', models.DateTimeField(auto_now=True)),
                ('isadmin_account', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('url_image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mander',
            fields=[
                ('id_mander', models.AutoField(primary_key=True, serialize=False)),
                ('ishavecar_mander', models.BooleanField()),
                ('ishavemoto_mander', models.BooleanField()),
                ('isactive_mander', models.BooleanField()),
                ('isvalidate_mander', models.BooleanField(default=False)),
                ('dateregister_mander', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_mander', models.DateTimeField(auto_now=True)),
                ('address_mander', models.CharField(max_length=100)),
                ('cc_mander', models.CharField(max_length=13)),
                ('image_id_image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('detail_request', models.CharField(max_length=255)),
                ('status_request', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('dateregister_request', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_request', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name_service', models.CharField(max_length=45)),
                ('detail_service', models.CharField(max_length=255)),
                ('image_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_userProfile', models.AutoField(primary_key=True, serialize=False)),
                ('name_userProfile', models.CharField(max_length=45)),
                ('lastname_userprofile', models.CharField(max_length=45)),
                ('phone_userProfile', models.CharField(max_length=10)),
                ('dateregister_userProfile', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_userProfile', models.DateTimeField(auto_now=True)),
                ('ismander_userProfile', models.BooleanField(default=False)),
                ('account_id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.account')),
                ('image_id_image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('brand_vehicle', models.CharField(max_length=20)),
                ('plate_vehicle', models.CharField(max_length=10)),
                ('model_vehicle', models.SmallIntegerField()),
                ('color_vehicle', models.CharField(max_length=45)),
                ('type_vehicle', models.CharField(choices=[('ninguno', 'Ninguno'), ('bicicle', 'Bicicleta'), ('bike', 'Motocicleta'), ('car', 'Automóvil')], max_length=10)),
                ('isverified_vehicle', models.BooleanField(default=False)),
                ('dateregister_vehicle', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_vehicle', models.DateTimeField(auto_now=True)),
                ('dateverified_vehicle', models.DateTimeField(auto_now=True)),
                ('image_id_image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.image')),
                ('user_id_userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Requestmanager',
            fields=[
                ('id_requestmanager', models.AutoField(primary_key=True, serialize=False)),
                ('status_requestmanager', models.CharField(choices=[('espera', 'En espera'), ('proceso', 'En proceso'), ('terminado', 'Terminado')], max_length=10)),
                ('detail_requestmanager', models.CharField(max_length=45)),
                ('dateregister_requestmanager', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_requestmanager', models.DateTimeField(auto_now=True)),
                ('image_id_image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.image')),
                ('mander_id_mander', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mander')),
                ('request_id_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='service_id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service'),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mander',
            name='user_id_userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('url_document', models.CharField(max_length=255)),
                ('isdocument_vehicle', models.BooleanField()),
                ('isverified_document', models.BooleanField()),
                ('type_document', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('SOAT', 'SOAT'), ('LICENCIA', 'Licencia'), ('OPERACION', 'Operación'), ('TECNOMECANICA', 'Tecnomecánica'), ('RECIBO', 'Recibo')], max_length=15)),
                ('dateregister_document', models.DateTimeField(auto_now_add=True)),
                ('dateupdate_document', models.DateTimeField(auto_now=True)),
                ('dateverified_document', models.DateTimeField(null=True)),
                ('user_id_userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
