# Generated by Django 4.2.7 on 2023-11-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname_userprofile',
            new_name='lastname_userProfile',
        ),
    ]
