# Generated by Django 4.2.7 on 2023-11-29 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_lastname_userprofile_userprofile_lastname_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url_document',
        ),
        migrations.RemoveField(
            model_name='mander',
            name='image_id_image',
        ),
        migrations.RemoveField(
            model_name='requestmanager',
            name='image_id_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image_id_image',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image_id_image',
        ),
        migrations.AddField(
            model_name='document',
            name='image_document',
            field=models.ImageField(default='', max_length=255, upload_to='imgDocs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mander',
            name='image_mander',
            field=models.ImageField(default='', max_length=255, upload_to='imgMander'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmanager',
            name='image_requestmanager',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imgRequestmanager'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_userProfile',
            field=models.ImageField(blank=True, null=True, upload_to='imgProfiles'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_vehicle',
            field=models.ImageField(default='', max_length=255, upload_to='imgVehicles'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='user_id_userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='mander',
            name='user_id_userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_service',
            field=models.ImageField(max_length=255, upload_to='imgService'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_id_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.account'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
