# Generated by Django 4.2.7 on 2023-11-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_document_user_id_userprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user_id_user',
            new_name='user_id_userProfile',
        ),
    ]
